### ISSUE TITLE
Bug #1036 resurfaced

### ISSUE THREAD

**Issue by Stwissel** [Apicurio/apicurio-studio#1087]
It has happened before (#1036) at it will happen again.
So say we all. ;-)

```
Something went wrong...
"https://studio.apicur.io/download?type=api&format=json&id=14792" is not a valid JSON Schema
Stack trace
SyntaxError: "https://studio.apicur.io/download?type=api&format=json&id=14792" is not a valid JSON Schema
    at Function.syntax (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:49:5419)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:61:70343

ReDoc Version: 2.0.0-rc.23
Commit: 88f8d74
```

**Comment by EricWittmann** [comment]
Would it be possible to grant me collaborator access to the failing API?  

eric.wittmann at gmail

If not that's OK but all my testing is green.  I assume editing works fine?

**Comment by Stwissel** [comment]
Edit works. API works

**Comment by Stwissel** [comment]
Invite sent

**Comment by EricWittmann** [comment]
OK I have reproduced this with no problem, but unfortunately the error information in the log is incomplete so I can't tell where it's originating from.  It's definitely coming from one of the commands though, I can tell that much.  But I can't tell more than that.  So I need to fix the logging issue and redeploy so we can get more information.

As a workaround, you can use the "Source" tab in the editor to get the full source of the API design that's broken.  You could then use Import to create a new API design from that content.  The resulting new API design will not be broken (because it will have a clean history - and no failing commands).

If you choose to do that, please don't delete the API design that's broken!  :)

**Comment by EricWittmann** [comment]
OK that's done - now I have some info to go on.  Should be able to get a fix quickly and push a hotfix today.  Hopefully!

**Comment by EricWittmann** [comment]
@Stwissel this has been fixed.  You should be able to download and preview the documentation once again without error.  Thank you for reporting the problem and for clearing being on the cutting edge of Apicurio Studio usage.

Also - you can remove me as a collaborator from that API now. :)
