### ISSUE TITLE
unable to login to apicurio-ui

### ISSUE THREAD

**Issue by lucamaf** [Apicurio/apicurio-studio#1257]
I have installed using OpenShift templates and commenting out the part dedicated to keycloak since I have my own keycloak version 11 running on Openshift.
I have created a user under the apicurio realm and the 2 clients as specified in the realm.json.
When trying to access using this user I can see this in apicuro-ui logs:

```
failed to turn code into token
[0m[31m2020-08-31 10:22:45,855 ERROR [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-1) status from server: 401
[0m[31m2020-08-31 10:22:45,855 ERROR [org.keycloak.adapters.OAuthRequestAuthenticator] (default task-1)    {"error":"unauthorized_client","error_description":"Client secret not provided in request"}
```

and this in keycloak logs:
`[0m[33m10:22:45,851 WARN  [org.keycloak.events] (default task-14) type=CODE_TO_TOKEN_ERROR, realmId=Apicurio, clientId=apicurio-studio, userId=null, ipAddress=192.168.50.1, error=invalid_client_credentials, grant_type=authorization_code
`

**Comment by EricWittmann** [comment]
This is really a Keycloak question, but I think the issue is with the configuration of your client in the Keycloak realm.  You've probably set the client to be `confidential` as its **Access type**.  For example:

![image](https://user-images.githubusercontent.com/1890703/91727316-85fbf280-eb6f-11ea-89ad-38b95b0182e3.png)

If that's the case, you will need to either change that to `public` or modify the Apicurio Studio configuration (in `keycloak.json`).  I don't have the instructions offhand for what changes you would need to make in `keycloak.json` - you'd have to look that up in the Keycloak docs.

**Comment by lucamaf** [comment]
you are right! as always super helpful, not sure why I thought it was a confidential client

**Comment by EricWittmann** [comment]
I **think** setting the client to be confidential adds another level of security by requiring a shared secret between the client and the server.  But the Keycloak guys would know better. :)
