### ISSUE TITLE
Question: APicurio to Existing PostgresqlDB with API Data

### ISSUE THREAD

**Issue by SusilRamarao** [Apicurio/apicurio-studio#1262]
I have data of Apicurio created APIs in an existing PostgresqlDB and I've installed Apicurio in another server. Through documentation I got to know that I should not use init flag while starting, since the data is already present in DB.

So my doubt is.. Does it affect the data in DB if I try to start an APIcurio instance connecting to that DB for first time?

**Comment by EricWittmann** [comment]
First, **always** back up your data (if possible) when doing something you aren't sure about.  :) :)

OK with that out of the way - Studio will automatically detect whether the database has already been initialized or not.  So if you connect a new  Apicurio Studio installation to an existing database (assuming the version of both Studio instances is the same) then you should have no problems.  Studio will examine your existing database and detect that it has already been initialized.  

If you are extremely paranoid you can set the `APICURIO_HUB_STORAGE_JDBC_INIT` environment variable to `false` which will cause Studio to **never** attempt to initialize the database.  Instead it will try to detect if the DB has already been initialized and fail to start up if not.

Note:  instead of the ENV var about you could alternatively set the `apicurio.hub.storage.jdbc.init` system property to `false` which will have the same effect.

**Comment by SusilRamarao** [comment]
Hi Eric, Thanks for the clarification. 👍
