### ISSUE TITLE
Improve on "Dereference All External $refs"

### ISSUE THREAD

**Issue by Stwissel** [Apicurio/apicurio-studio#1368]
When I import a schema I get a snippet like this:

```
"Alert": {
                "$ref": "apicurio:39013#/components/schemas/Alert"
            },
```
when I export and select **Dereference All External $refs"** it changes to:

```
"Alert": {
                "$ref": "#/components/schemas/Alert1"
            },
```
with `Alert1` containing the actual Schema. Would it be possible to have `Alert` contain all definitions instead of the extra reference?

**Comment by EricWittmann** [comment]
I think in some/many cases this would make sense, but dereferencing is more complicated than you might think, so we would need to think through the implications.

Pulling in @jsenko because he implemented the Dereferencer in the Apicurio Data Models project.

Let's start the analysis here - I'll add some thoughts to get the ball rolling.

If we saw a pattern like what is described above, where there is already a locally defined component that is a simple `$ref` to some other document, we should be able to safely inline it without creating another component.  We can perhaps think of these as "simple imports" or "identity references" or something.  Further, if the same `$ref` exists elsewhere in the document, we could simply change the reference to the local component and do nothing else.  So in the example above, we could do this:

1. Replace the local `Alert` with the content found at `apicurio:39013#/components/schemas/Alert`
2. Find/Replace all other references in the document to `apicurio:39013#/components/schemas/Alert` with `#/components/schemas/Alert`

I can't see why this would be a problem.

Maybe we could implement this as a first phase, and then continue with the current algorithm afterwards.  This would be particularly helpful in Apicurio Studio, since this "simple import" pattern is what our editor produces.

**Comment by EricWittmann** [comment]
This has been implemented here:  https://github.com/Apicurio/apicurio-data-models/pull/228
