### ISSUE TITLE
Feature request: [codegen] add configuration to return jaxrs Response

### ISSUE THREAD

**Issue by famartinrh** [Apicurio/apicurio-studio#1515]
From discussion https://github.com/famartinrh/apicurio-registry/pull/21#discussion_r634601753

Add the ability to configure (maybe with an extension property) the codegen to generate a jaxrs interface with a method that returns  `Response` instead of the java type of the entity

**Comment by EricWittmann** [comment]
Fixed in https://github.com/Apicurio/apicurio-studio/commit/72f0e669c51e932959699cded77507baef03ec93

You can add the following property to your response (must be a 2xx response):

`"x-codegen-returnType" : "javax.ws.rs.Response"`

The value of the custom property must be `x-codegen-returnType` and the value should be a fully qualified Java classname.  The property must be set on the Media Type.  An example would be:

```yaml
get:
    responses:
        '200':
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Widget'
                    x-codegen-returnType: javax.ws.rs.core.Response
            description: Successful response - returns a single `Widget`.
    operationId: getWidget
    summary: Get a Widget
    description: Gets the details of a single instance of a `Widget`.
```

**Comment by EricWittmann** [comment]
Note: our internal Apicurio Studio instance is being updated with this new feature right now.  Will be done in 15 minutes. :)  This feature will be in the next release of Studio.
