### ISSUE TITLE
Require images for ARM64

### ISSUE THREAD

**Issue by odidev** [Apicurio/apicurio-studio#1517]
Hi Team,

I am trying to use apicurio-studio images in arm64 machine, but arm64 tag is not available for any of the images.

I have built API, UI, and WS images on the arm64 machine successfully. I have added buildx in GitHub actions but it requires the installation to be done from dockerfile to build target jars and run them.

Do you have any plans on releasing arm64 images?

If interested, I will raise a PR with buildx changes.

**Comment by EricWittmann** [comment]
We don't have any current plans to release arm64 images.  I'd be very happy to see a PR with the required changes.

**Comment by Avinash828** [comment]
@EricWittmann,  

I have added a job for releasing docker images for arm64. Please have a look 

**Commit Link -**  https://github.com/odidev/apicurio-studio/commit/3b57852b9ffa5261ba26bb159045acd0638be8a4 

**GHA Logs Link -**  https://github.com/odidev/apicurio-studio/runs/5770938137?check_suite_focus=true 

**DockerHub Images Links -** 

- **Apicurio-studio-api:-** https://hub.docker.com/repository/docker/odidev/apicurio-studio-api 
- **Apicurio-studio-ws:-** https://hub.docker.com/repository/docker/odidev/apicurio-studio-ws 
- **Apicurio-studio-ui:-** https://hub.docker.com/repository/docker/odidev/apicurio-studio-ui 

If you are fine with the above changes, I am happy to raise a PR.

**Comment by odidev** [comment]
@EricWittmann,

I have added a job for releasing docker images for arm64. Please have a look

**Commit Link -** https://github.com/odidev/apicurio-studio/commit/3b57852b9ffa5261ba26bb159045acd0638be8a4

**GHA Logs Link -** https://github.com/odidev/apicurio-studio/runs/5770938137?check_suite_focus=true

**DockerHub Images Links -**

- **Apicurio-studio-api:-** https://hub.docker.com/repository/docker/odidev/apicurio-studio-api
- **Apicurio-studio-ws:-** https://hub.docker.com/repository/docker/odidev/apicurio-studio-ws
- **Apicurio-studio-ui:-** https://hub.docker.com/repository/docker/odidev/apicurio-studio-ui

If you are fine with the above changes, I am happy to raise a PR.

**Comment by EricWittmann** [comment]
@carlesarnal any thoughts on this?

**Comment by carlesarnal** [comment]
I think this is an interesting idea. That said, I would have expected modifications to the current job to release the images for arm using buildx to build the images for both platforms instead of creating a fresh new job. @odidev please, open a PR, and we can continue the discussion there.

**Comment by EricWittmann** [comment]
@riprasad Since you did this recently for Registry, could you implement it for Studio as well? :)

**Comment by odidev** [comment]
@EricWittmann 

I have successfully built ARM64 image of apicurio-studio-auth on my local ARM64 machine and, I could see that the image for amd64 is released [here](https://hub.docker.com/r/apicurio/apicurio-studio-auth/tags) but there is no specific release process mentioned. If I could get the release process for images, I would add ARM64 and raise PR for the same.

**Comment by EricWittmann** [comment]
Sorry for the delay, @odidev and thank you for the offer.  Right now the apicurio-studio-auth image is just released manually, because we don't release it very often.

So really we need to create a new separate GH workflow for this!

@riprasad wdyt?  Easy to create a new standalone workflow for apicurio-studio-auth?  I think it should initially be just manually triggered, but we can figure out an appropriate auto=trigger later.

The source for that image is here:

https://github.com/Apicurio/apicurio-studio/tree/master/distro/openshift/auth

**Comment by riprasad** [comment]
@odidev I was able to build the apicurio-studio-auth image in arm64, which is a bit surprising to me since the base image is only available for amd64. I thought it was also necessary for the base image to be available for the target platform.
![Screenshot from 2022-05-17 14-21-11](https://user-images.githubusercontent.com/61964599/168775446-4061eeda-5fce-4d59-b27c-d3c29f855ebd.png)

**Comment by odidev** [comment]
@riprasad, As arm64 image of keycloack is not present on docker.io, we need to use the [keycloak](https://quay.io/repository/keycloak/keycloak?tab=tags) image available in quay.io.
