### ISSUE TITLE
Red Hat SSO support

### ISSUE THREAD

**Issue by tadashi-hata** [Apicurio/apicurio-studio#1567]
Hi,

I'm really interested in use APICurio, I know that it is currently using Keycloak 11, but we are using Red Hat SSO 7.4 that is based on Keycloak 9.0.13.
Is there any compatible issue ralated to using different version of RH-SSO?
Is there any reference guide or documentation where I could find the minimum version of Keycloak?

Thanks in advance!

Tadashi.

**Comment by carlesarnal** [comment]
Hi @tadashi-hata, we do not have a minimum version documented. That said, we have the public version of the application running in the cloud with a relatively old version of Keycloak (4.8) so I don't see any problem for 9.0.13 not working since the application is working fine with previous and newer versions. I think it should be a matter of migrating the data in Red Hat SSO.

**Comment by tadashi-hata** [comment]
Thanks a lot @carlesarnal! 
Another quick question is about the helm configuration itself. I tried to import the helm configuration that was in the ApiCurio guide into my RH-SSO, but as the version is too different I couldn't import it successfully. Is there any baby steps guide to set up the helm with all clients that are needed?

**Comment by carlesarnal** [comment]
Hi @tadashi-hata, sorry for the delay.

[This](https://www.apicur.io/studio/docs/setting-up-keycloak-for-use-with-apicurio) is probably the best information I can provide. Is not directly related to helm but it describes how the Keycloak configuration should look like. Let me know if you have any problems or any issues.

Thanks!
