### ISSUE TITLE
Unable to create new API. Organization drop down blank.

### ISSUE THREAD

**Issue by walljt** [Apicurio/apicurio-studio#203]
I have my Github account linked to Apicurio, but when I try to create a new API, no matter what path I put into the Resource field before the .json filename, the Create API button remains inactive. The Organization drop down also remains blank. 

Is their a specific organization or project name that Apicurio expects? Is there a specific path format required?

**Comment by EricWittmann** [comment]
That's very odd.  The organization drop down should get populated with all of the orgs that you have access to.  If that is failing then that form won't work.

How are you trying apicurio?  Did you download the quick start or are you trying the online version?

**Comment by walljt** [comment]
The online version.

**Comment by EricWittmann** [comment]
Are you a member of any GitHub organizations?  Normally that shouldn't matter because your GitHub login ID acts as its own GH org, but I think there might be a bug in the online version of Apicurio right now where your personal org isn't showing up in the drop-down. :(

If you *are* a member of at least one GitHub organization, then the API call to retrieve your orgs must be failing for some reason.  Can you check to see if you have any errors in your browser's JavaScript console?

**Comment by EricWittmann** [comment]
Also note that the next major release of Apicurio will not require account linking in order to create or add APIs to the studio.  Instead, we'll be storing the API content in the Apicurio database itself, rather than rely on the source control systems for that.  There will continue to be integration with e.g. GitHub, but only for importing APIs and for "publishing" APIs on-demand.  

Not relevant to your problem just an FYI for the future. :)

**Comment by walljt** [comment]
I am a member of one org, but I don't think it's grabbing it. From the front end, I can't see any errors or exceptions in the browser. 

However, looking through the classes and the API, here is my guess at what's happening...

From the browser events I see this being called...
https://release-apistudio.rhcloud.com:443/api-hub/accounts/GitHub/organizations

It seems that the "GitHub" should be "github". Both in the API description:
  - apicurio-studio/back-end/hub-api/src/main/resources/studio-api.json

      "parameters": [
        {
          "name": "accountType",
          "in": "path",
          "description": "Account type - must be \"github\".",
          "required": true,
          "type": "string"
        },

and in the Enum for the account type LinkedAccountType:

- apicurio-studio/back-end/hub-api/src/main/java/io/apicurio/hub/api/beans/LinkedAccountType.java
--  GitHub("github")

**Comment by EricWittmann** [comment]
I can see how you'd reach that conclusion from the code but in reality (and after testing to make sure), the value of "GitHub" is OK.  I suspect something else must be going on (I just ran a test using my account).

If you don't mind a little debugging, could you try this in a shell:

```
USER=jtwall
PASS=your_password123
echo "grant_type=password&client_id=apicurio-studio&username=${USER}&password=${PASS}"
RESULT=`curl -s --data "grant_type=password&client_id=apicurio-studio&username=${USER}&password=${PASS}" https://auth-apistudio.rhcloud.com/auth/realms/apicurio/protocol/openid-connect/token`
echo $RESULT
TOKEN=`echo $RESULT | sed 's/.*access_token":"//g' | sed 's/".*//g'`
echo $TOKEN
curl -s -H "Authorization: bearer ${TOKEN}" https://release-apistudio.rhcloud.com:443/api-hub/accounts/GitHub/organizations
```

I've tried the above on a centos shell and on a Windows mingw64 shell and it works in both, which is fun.  :)

In my case the output of the final command is a JSON array of my GitHub orgs (but my personal org is missing).

**Comment by walljt** [comment]
$ curl -s -H "Authorization: bearer ${TOKEN}" https://release-apistudio.rhcloud.com:443/api-hub/accounts/GitHub/organizations
[]
:-(

**Comment by walljt** [comment]
I got it working. I had to explicitly go into Github and grant Apicurio access to the organization as well.

**Comment by EricWittmann** [comment]
Ah ha!  That's a pain in the butt.  Glad you figured it out - apologies for not thinking about that earlier as I've run into that issue in the past (where a subset of orgs were not appearing in the list).

Of course we've def. identified a bug where the user-org is not appearing.  I've written that up separately here:  https://github.com/Apicurio/apicurio-studio/issues/204
