### ISSUE TITLE
Page Not Found error when trying to open an existent model from github.

### ISSUE THREAD

**Issue by cvgaviao** [Apicurio/apicurio-studio#208]
I'm trying to open an example from OpenApi spec that is hosted in github and I'm getting a Page Not Found error. 

> You attempted to navigate to a page that does not exist! I guess you should either hit the back button or go back to the Dashboard (button below). 

The file is here: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/callback-example.yaml

Tried to open an example from apicurio repository and it worked: **https://github.com/Apicurio/apicurio-studio/blob/master/back-end/hub-api/src/test/resources/io/apicurio/hub/api/beans/simple-api-3.0.json**
would be the type of the file, json vs yaml ?

**Comment by EricWittmann** [comment]
Note: this is still a valid bug report because we need better error messages when Adding/Importing an API.  If the resource cannot be found (e.g. when importing from a URL) then we should report that (**not** report a "Page Not Found" error).  If the resource exists but is an incorrect format, we should report that differently.

**Comment by david4096** [comment]
I couldn't get my OpenAPI 3 JSON or the example linked above to work today. Importing from a URL didn't work for:

https://github.com/Apicurio/apicurio-studio/blob/master/back-end/hub-api/src/test/resources/io/apicurio/hub/api/beans/simple-api-3.0.json

or

**Comment by EricWittmann** [comment]
Hi @david4096 - the first URL is failing because there really isn't any content at that URL.  At least when I click on that link there's no file.  In fact, there is no `resources` folder within `src/test` for that module:

https://github.com/Apicurio/apicurio-studio/tree/master/back-end/hub-api/src/test

However, there **is** obviously content at the second URL.  The reason it's not working in Apicurio is that we unfortunately don't yet support pulling in content from branches (only master).  This is clearly missing functionality, as it's not difficult to support branches.

That said, I think we're going in the direction of being able to Add/Import an API design from an arbitrary URL instead of from the various source control systems via their respective APIs (which is what we do now, purely as a holdover from when we more heavily leaned on those systems to store the data).  I'll bump up the priority of the "import from URL" feature and have it included in the next version.

For now, what you can do as a workaround is store any APIs you want to Add/Import into the master branch of any github repository (perhaps create a repository for this purpose) and import from there.

**Comment by EricWittmann** [comment]
I've added a ticket to support branches in source control:

https://github.com/Apicurio/apicurio-studio/issues/222

However I think that importing content from arbitrary URL will be a more useful feature, so I'll address that first.

**Comment by david4096** [comment]
Hi @EricWittmann thanks for the explanation!
