### ISSUE TITLE
Online version doesn't give the option to "store the project in"

### ISSUE THREAD

**Issue by dcu** [Apicurio/apicurio-studio#210]
So there's no way I can get the spec files.

**Comment by EricWittmann** [comment]
Hi @dcu - unfortunately I messed up a bit last night and accidentally pushed a snapshot version of Apicurio into openshift.  Oops. :(

I'm going to be iterating on that snapshot the rest of this week to add some missing functionality so that it's usable.  The two primary features are:

1. Download API design (downloads as JSON or YAML)
2. Publish API to GitHub/GitLab/Bitbucket

I'm hopeful that I'll have at least (1) completed by the end of today.

Apologies for the inconvenience.

**Comment by dcu** [comment]
downloading would be awesome

**Comment by EricWittmann** [comment]
This feature is now live.  You can download the API design from the API Design Details page.  There is a quick button to download it as YAML and there are two new menu items in the "..." menu - one for JSON and one for YAML.

**Comment by dcu** [comment]
awesome, thanks a lot! how can I donate to the project?

**Comment by EricWittmann** [comment]
Well, it's a Red Hat sponsored project so there's no way (or need) to donate money.  But feedback and especially code contributions are *always* welcome!  :)

You could also tweet about it - that's always helpful.
