### ISSUE TITLE
No Github icon when creating a new API

### ISSUE THREAD

**Issue by EmanShaaban** [Apicurio/apicurio-studio#289]
I'm using apicurio-studio-0.2.7.Final.
There is no Gitlab or Github or Bitbucket icons when creating new API.
I tried to create new API from the live Version and from a local installation
![screenshot from 2018-04-30 11 50 31](https://user-images.githubusercontent.com/2835223/39425938-0383676c-4c7e-11e8-82dd-d80a0cfd512b.png)
![screenshot from 2018-04-30 11 50 46](https://user-images.githubusercontent.com/2835223/39425941-08184810-4c7e-11e8-98c4-58d90a348a63.png)

**Comment by EricWittmann** [comment]
Early versions of Apicurio didn't have an actual server component, so all content was stored in e.g. GitHub.  I believe the "5 minute" video on the project site may still reference that.  Things have change now, however.  Apicurio does have a real backend and so your API content is stored there as you make changes.  This also enables the new collaborative editing features, where multiple users can simultaneously edit an API.

The GitHub/GitLab/Bitbucket account linking is still useful, however, because once you have created/edited your API you can **publish** it to one of the source control systems.  There is an action from the API Details page where you can publish the API:

![image](https://user-images.githubusercontent.com/1890703/39427059-553f6fb6-4c50-11e8-8d42-20523be6e29c.png)

If you choose that action, you can then fill out some details on the resulting form to publish the OpenAPI document into e.g. GitHub:

![image](https://user-images.githubusercontent.com/1890703/39427109-93cc13ec-4c50-11e8-9904-4eef9ec61c5c.png)
