### ISSUE TITLE
Allow updating the source for the entire API

### ISSUE THREAD

**Issue by sherl0cks** [Apicurio/apicurio-studio#349]
I'm switching between various editors to work on my spec, but I cannot reimport the changes from other editors to apicurio in order to continue working on the same API. The only way to reimport seems to be to create a new API which would lose history, collaborators etc. 

I think most users will switch back and forth between IDE and apicurio, so an "Edit Source" for the whole doc, not just snippets, would be good.

**Comment by EricWittmann** [comment]
I think for this feature to be done correctly, I may need to implement a smarter version of it.  Specifically something that detects the differences and only applies those differences to the model.  Otherwise I suspect a full replacement of the source will play havoc with collaborative undo/redo.

Something to consider, at least.

**Comment by sherl0cks** [comment]
That is fair. Is it the collaborative part that is an issue here? For a single user I would expect this to work like a normal editor when I have the changes in my clipboard, open the file I want to overwrite and then  Ctrl+a and the Ctrl+v.

**Comment by EricWittmann** [comment]
Yeah if not for collaboration then it would be much easier.  As you say you would just switch to the Source tab and replace everything with new content.

And honestly I'm not 100% sure that it would be a problem for collaborative undo/redo.  I'd need to put the ol' thinking cap on for that. :)
