### ISSUE TITLE
Improvement - Collaboration

### ISSUE THREAD

**Issue by gigaga** [Apicurio/apicurio-studio#351]
Currently, to enable collaborate work, each API owner has to launch invitation for each others members (individually.
I will be great if we can share our API for everyone (authenticated users) too.

**Comment by EricWittmann** [comment]
Thanks for the PR on this.  However, I'm a little concerned with maintenance of the SQL layer long-term.  This change requires that I maintain two separate SQL statements for a number of DB calls.  I'm wondering what you'd think if rather than having a global setting that effectively disables the ACL, we instead add a feature whereby an API owner can mark an API as "public".  So the "share with everyone" feature would need to be turned on for each API individually, but would allow both "public" and "private" APIs to exist simultaneously.  It would also mean that I can maintain a single set of SQL statements, which should be better long-term I think.

Thoughts?

**Comment by gigaga** [comment]
I added a global setting to avoid to change database model too :D
In fact, in my team (30 persons), add write right for each people individually is not possible. Allow to declare some API as public will be great. Private mode will be never used...

**Comment by EricWittmann** [comment]
OK understood, thanks!

**Comment by EricWittmann** [comment]
This has been resolved by:  https://github.com/Apicurio/apicurio-studio/pull/355
