### ISSUE TITLE
Description & Version incorrect

### ISSUE THREAD

**Issue by gigaga** [Apicurio/apicurio-studio#354]
Currently, after editing an API, if I edit another API, description & version fields are filled with the previous API. Furethemore, this incorrect data is stored in database because "onMessage" is executed (in EditApiDesignEndpoint)

Thx

**Comment by EricWittmann** [comment]
I must admit this is pretty shocking. :(  I'll make this today's priority and it might warrant an emergency build...

**Comment by EricWittmann** [comment]
Note: it *seems* to be duplicating the most recent change, whatever it might be.  Very bad.

**Comment by gigaga** [comment]
I am trying to understand too. Maybe, the problem is due to "openEditingSession" method in apis.service.ts.

**Comment by EricWittmann** [comment]
OK I've found and fixed the problem.  Unintended consequence of another change.  But basically I have an angular service shared across various editor components called CommandService.  It's used to communicate when a sub-component causes a command (change) to be executed.

But I wasn't resetting the service each time the editor was opened.  The service exposes an Observer that the editor uses to listen for commands that need to be executed.  Because the service wasn't reset between editing sessions, that same Observer was used every time.  So the last executed Command was being dispatched to the new editor immediately when it subscribed.

The solution is to reset the service when the editor is initialized. :)

**Comment by gigaga** [comment]
Great!!! Thx!

**Comment by gigaga** [comment]
Where is your commit?

**Comment by EricWittmann** [comment]
Just testing now. :)

**Comment by gigaga** [comment]
:)

**Comment by EricWittmann** [comment]
OK looks good now.  Thanks for finding and reporting this!

**Comment by gigaga** [comment]
It's work! Thanks!
