### ISSUE TITLE
Support for ReDoc preview

### ISSUE THREAD

**Issue by Devin-Grant** [Apicurio/apicurio-studio#373]
I would be nice to view the doc while editing  in Apicurio using ReDoc (and Swagger UI).

**Comment by Devin-Grant** [comment]
I thinking there should be a button which will display the OpenAPI in ReDoc in a new window.  The user should be able to refresh the page to display the latest changes made in Apicurio.

**Comment by EricWittmann** [comment]
OK sounds reasonable.  :)  Thanks for the input.

**Comment by EricWittmann** [comment]
I've finally added the ReDoc preview feature to Apicurio.  You can preview ReDoc based documentation either from the API Details page or from the API Editor.  If you preview from the editor, it will be a "Live Preview" and so the documentation will automatically refresh whenever you edit the API.

**Comment by 19wildcard18** [comment]
Also, live reloading doesn't seem to be working for me. The page does not reload on save, also there is no real-time communication in my developer console.

I'm going to debug this later and update here, I'm currently at work.

**Comment by EricWittmann** [comment]
Thanks for the feedback.  I agree that supporting additional renderers would be a nice feature to have.  The question is how to configure that.  In the current version of Apicurio it could just be a global setting (i.e. a system property).  However once I get around to creating organizations, teams, etc then it would be nice to configure the preferred renderer at either the Org or Project level.

I have some thoughts about the plugins idea that I will add to #612 instead of here. :)

As for publishing different versions of the API under unique slugs without requiring auth, that is a feature that is already on the roadmap and tracked in #526

**Comment by EricWittmann** [comment]
@19wildcard18 the live reloading only works if you open the preview window from the editor.  If you open it from the API Details page, then it will NOT auto-refresh.

Refresh should happen whenever a local change is made to the API (changes made by remote collaborators will not trigger an auto-refresh of the preview).
