### ISSUE TITLE
Facing issue while linking Github account

### ISSUE THREAD

**Issue by raghurakesh** [Apicurio/apicurio-studio#377]
I have downloaded Apicurio and have followed the documentation to setup apicurio and keycloak. I am facing issues while linking my Github account. The account gets successfully linked in github, but on the redirect, there is an error. 

Appreciate if someone can help me with this. Putting all the screenshots with the errors and logs.

**Error log from Keycloak**

<img width="1287" alt="screen shot 2018-07-31 at 5 07 37 pm" src="https://user-images.githubusercontent.com/39341415/43450391-34b8b29c-94e5-11e8-96ab-72ce00ed2524.png">

<img width="1079" alt="screen shot 2018-07-31 at 5 07 56 pm" src="https://user-images.githubusercontent.com/39341415/43450390-34615d8a-94e5-11e8-8ae9-d771333dfb83.png">

<img width="1276" alt="screen shot 2018-07-31 at 5 08 15 pm" src="https://user-images.githubusercontent.com/39341415/43450389-34056c6e-94e5-11e8-82b2-f03e05767a4d.png">

**Github Account settings**

<img width="575" alt="screen shot 2018-07-31 at 5 08 39 pm" src="https://user-images.githubusercontent.com/39341415/43450388-33adb00a-94e5-11e8-972c-4c6f4e50f63c.png">

**Keycloak admin console settings**

<img width="775" alt="screen shot 2018-07-31 at 5 09 17 pm" src="https://user-images.githubusercontent.com/39341415/43450384-3356d078-94e5-11e8-9e7b-e1af5ca281fa.png">

**Error in Apicurio**

<img width="623" alt="screen shot 2018-07-31 at 5 18 22 pm" src="https://user-images.githubusercontent.com/39341415/43450660-c661b81a-94e5-11e8-8b6f-58cee384de14.png">

Versions used : 
Keycloak - 4.1.0
Apicurio-studio - 2.13

**Comment by EricWittmann** [comment]
What are your GitHub identity provider settings?  (make sure you redact the Client ID before posting the info).  Here are the settings we use for **studio.apicur.io**:

![image](https://user-images.githubusercontent.com/1890703/43457812-07b331cc-9496-11e8-90f3-183d7fb32d31.png)

**Comment by EricWittmann** [comment]
Some more info and some questions.  :)

1. Are you trying to **login** using GitHub or are you trying to link your account?

2. For reference, the error is coming from Keycloak here:  

https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/social/github/GitHubIdentityProvider.java#L98

3. Do you have any [email addresses associated with your GitHub account](https://github.com/settings/emails)?  Is it possible to NOT have any?  I don't know.

4. Can you try creating a GitHub [Personal Access Token](https://github.com/settings/tokens) and then trying this?

```
curl -H "Authorization: Bearer <PERSONAL-ACCESS-TOKEN-HERE>" https://api.github.com/user/emails
```

5. I suspect the problem is that, for some reason, you don't have a primary email address assigned in GitHub and that Keycloak is perhaps trying to use the GitHub emails API to find it.  And I think that's failing because when we configure the GitHub identity provider in Keycloak we don't ask for enough privileges to access the GitHub Emails API.  So try adding **user:email** to the list of **Default Scopes** in the GitHub Identity Provider settings in Keycloak.  For example:

![image](https://user-images.githubusercontent.com/1890703/43458827-9bf56910-9499-11e8-83ca-e0c62f31e04b.png)

**Comment by raghurakesh** [comment]
Hi Eric,

Thanks for the detailed feedback on the possible issues.

The issue is solved. As you rightly pointed out, the issue was due to the email address in GitHub. I had set the email address in Github as private, which means it will not be shared. And when the service was trying to retrieve the email address it failed. I updated the email address, and now it works.. 👍 

Thanks once again for your time.
