### ISSUE TITLE
Keycloak page not found error

### ISSUE THREAD

**Issue by vnalla** [Apicurio/apicurio-studio#380]
I have followed all the steps up to Step 6 except the optional one. I am getting page not found error.
Both Apicurio and Keycloak are running on the same machine with OS Ubuntu 16.04.
Keycloak version 4.1.0
Apicurio version 0.2.13
Java 1.8
http://192.168.2.3:8080/auth/realms/apicurio-local/protocol/openid-connect/auth?response_type=code&client_id=apicurio-studio&redirect_uri=http%3A%2F%2F192.168.2.3%3A8180%2Fstudio%2F&state=7c67e841-c25d-452a-a829-882585449e1a&login=true&scope=openid

![image](https://user-images.githubusercontent.com/11826854/43592407-7c3eef32-9643-11e8-9aa9-375a8f97af5d.png)

**Comment by EricWittmann** [comment]
What is the realm name you've configured in Keycloak?  The URL you included indicates it is "apicurio-local" but the documentation is "apicurio".  The **apicurio-local** realm is something configured on the cloud version of Keycloak that I'm running to make the Quickstart run easily "out of the box".  Perhaps it's causing a bit of confusion.

**Comment by vnalla** [comment]
I followed the documentation and it is apicurio. I have changed it to apicurio-local and it is working now. thanks!

**Comment by EricWittmann** [comment]
Glad it's working now!

Although actually what I meant was that your settings in **Apicurio** might mistakenly be referring the **apicurio-local** realm.  The documentation mentions changing that (in the `standalone-apicurio.xml` file) from **apicurio-local** to **apicurio**.  In particular, there is a system property in that file:

```
<property name="apicurio.kc.auth.realm" value="apicurio"/>
```

I think that setting is probably **apicurio-local** for you, which is why the connection between apicurio and keycloak wasn't working for you.  Changing the realm name in Keycloak is fine!  But you could also have changed the value there.
