### ISSUE TITLE
Editor: Distorted UI when switching from GET to PUT of a path

### ISSUE THREAD

**Issue by 0815fox** [Apicurio/apicurio-studio#416]
I have a path and am in the GET-Window. When I click PUT on the left hand tool bar, the UI is distorted, the "Request Body" section overflows the other sections.

Clicking PUT again or folding and unfolding the "Request Body" section repairs that issue temporarily.

This happens in Firefox 60.2.0esr (64-Bit) on Ubuntu MATE

![grafik](https://user-images.githubusercontent.com/8955528/45300464-b1aee980-b50e-11e8-97e4-5eeac63e7789.png)

**Comment by EricWittmann** [comment]
Are you sure this isn't "as-designed"?  ;)

**Comment by 0815fox** [comment]
If it were, then I'd like to file this bug report against the design.

**Comment by EricWittmann** [comment]
This should be fixed in the next release.  I'm still not 100% sure that the behavior is what I want (when switching between operations in the same path).  What will happen is that the "collapsed" state will be preserved for all sections, which seems right.  On the other hand, maybe not.  You'll have to play around with it and give me your opinion on the behavior.  :)
