### ISSUE TITLE
Editor: All Descriptions should allow multi line (and have a bigger input box)

### ISSUE THREAD

**Issue by 0815fox** [Apicurio/apicurio-studio#421]
![grafik](https://user-images.githubusercontent.com/8955528/45414170-18e9ac80-b67b-11e8-95a3-ec527917f089.png)

EOM

**Comment by EricWittmann** [comment]
There are two parts to this in my mind.  The first is that there needs to be more area available for the control itself.  That's actually actively being worked on as I am in the middle of renovating the UX.  Part of that renovation is updating the L&F of most of these "lists" of entities (properties, parameters, responses, etc).  And the updated UI will have more room for the description (at a cost of requiring two clicks to edit a description instead of the current 1-click).  

The second part is to replace the current inline description editor (which is a simple textarea) with a markdown editor.  There's an issue already in for that.

**Comment by EricWittmann** [comment]
Note: I'll close this out once I've updated the L&F for all of the relevant entities...

**Comment by 0815fox** [comment]
Great! As long as you can submit with `Ctrl + Return` there are no additional clicks at all ;-)
