### ISSUE TITLE
Cannot link to bitbucket account anymore

### ISSUE THREAD

**Issue by 0815fox** [Apicurio/apicurio-studio#425]
I had my apicurio linked to bitbucket for easy deployment. However, that feature does not work anymore since yesterday. Maybe they changed something in their API. I removed the linked bitbucket account and tried to connect again, but I get:

![grafik](https://user-images.githubusercontent.com/8955528/45468868-3b390400-b727-11e8-9959-8bafffa2e273.png)

Can anyone who uses bitbucket confirm that issue?
Any ideas?

**Comment by EricWittmann** [comment]
Perhaps there was a problem with your token - the Account Linking feature with Bitbucket is a bit flaky (or possibly Apicurio needs to refresh the bitbucket bearer token manually).

If you send me your email address (or even just the part before the @ ) I should be able to reset your account in Keycloak so that you can re-create the account link.

Note that Keycloak currently has a bug that is preventing Apicurio from deleting the account link.  Hopefully there will be a fix to that soon...

**Comment by 0815fox** [comment]
Your reset finally resolved the issue for now. So from my side this issue is resolved, however, you may want to keep this issue open as a reminder for a general improvement on this topic. Leaving it up to you whether to close it or not.

**Comment by EricWittmann** [comment]
Closing as I have this tracked in Keycloak's issue tracker... glad it's working (at least for now)!  If it happens again just let me know - easy enough for me to delete the token in the Keycloak UI.

Note: what's missing is a way to delete it via the Keycloak API.  That's what I'm waiting on.
