### ISSUE TITLE
GitLab connector does not fetch all groups/projects/branches

### ISSUE THREAD

**Issue by csoszka** [Apicurio/apicurio-studio#466]
GitLab provided APIs are paginated:
https://docs.gitlab.com/ee/api/branches.html#list-repository-branches

The default  perPage is 20. Only the first 20 item are fetched now for groups, projects (user and group too), branches

The Group list API also work with two params:
https://docs.gitlab.com/ee/api/groups.html#list-groups
**min_access_level:** can be ignored, but would be nice to have as configuration
**all_available:** it should be configurable, because the default value for admins is true (in our company local gitlab this means I get more than 100 groups, which makes the dropdown useless in the UI)

**Comment by EricWittmann** [comment]
I thought paging had been implemented in the GL connector. :(  But I see that of course you are right and it hasn't.

I'll also make both those properties configurable (globally) and default `all_available` to 30.  Does that sound like a reasonable default?

**Comment by EricWittmann** [comment]
Oh - you already opened a PR for this.  Nice!  Thanks very much.  Will review ASAP.

**Comment by csoszka** [comment]
> I thought paging had been implemented in the GL connector. :( But I see that of course you are right and it hasn't.
> 
> I'll also make both those properties configurable (globally) and default `all_available` to 30. Does that sound like a reasonable default?

min_access_level has precedence over all_available.
As I see, the min_access_level = 30 and the all_available = false means the some for admins, but I've not tested all possible combinations.

**Comment by EricWittmann** [comment]
Yeah sorry - I meant to say `min_access_level` to 30 maybe.  I'll play around with it some more now that I've merged in your changes. :)

**Comment by EricWittmann** [comment]
Also I think it's perhaps time for me to implement a drop-down control that allows the user to filter the results by typing in a search box.

**Comment by EricWittmann** [comment]
To my last point, see https://github.com/Apicurio/apicurio-studio/issues/468

**Comment by EricWittmann** [comment]
Closing this issue now that we are properly handling paging for GitLab data.  In addition, I have updated the drop-down control to better handle large numbers of items by automatically adding a filter control when there are more than 20.  The filter control allows the user to type some text to filter the list of items.  The control still needs e.g. better keyboard handling, but is at least better now.

Note that I modified the paging support to use the `Link` HTTP response header (as recommended by the GitLab docs) instead of manual paging.  Basically works the same.  Thanks again @csoszka for the PR - much appreciated!
