### ISSUE TITLE
Allow me to make other users on a project as owners

### ISSUE THREAD

**Issue by thesteve0** [Apicurio/apicurio-studio#504]
I don't see a way to designate other users as owners as well. This makes the projects really fragile to change in personnel, alien abduction, or even going on vacation. Can you please allow multiple owners and a means for the owner to make someone else a co-owner

**Comment by EricWittmann** [comment]
You know it's funny - we were just reviewing the collaboration stuff today and I noticed this very problem (the inability to elevate someone from a collaborator to an owner).

Longer term we will be introducing Organizations, Projects, and Teams to Apicurio.  At that point, collaboration will be handled by creating Teams rather than the current approach of one-off invitations we have today.  But until then, I agree that a simple change that allows an Owner to make more Owners is a good one (and relatively simple).

I actually think the back-end already supports this, I just never got around to adding support in the front-end.

**Comment by EricWittmann** [comment]
PS: would you say the vacation use-case is more prevalent than the alien abduction one?  Asking for a friend.

**Comment by thesteve0** [comment]
Yeah, at least in my experience, vacations are more prevalent than alien abductions. 

I try to use alien abduction rather than being hit by a bus - seems more exciting and less gruesome 😄

**Comment by thesteve0** [comment]
Yup already used it twice - thanks so much! You should definitely add this feature to the release notes at the top of the list
