### ISSUE TITLE
[Question] Is there a config item for local Bitbucket (like local Gitlab)?

### ISSUE THREAD

**Issue by jamesgallagher-ie** [Apicurio/apicurio-studio#508]
I only recently noticed https://apicurio-studio.readme.io/v0.2.15/docs/using-a-local-installation-of-gitlab and wondered if there's a similar option for Bitbucket to setting 'apicurio.hub.gitlab.api'? Day job has Bitbucket Server so it would be nice to integrate with that as 3rd party cloud for source code isn't permitted. 

(I'll probably install a local Gitlab while I "kick the tyres" - my goal here is to find an easy to use tool for fellow BAs/POs who work with API requirements)

**Comment by EricWittmann** [comment]
Yes - all three systems (github, gitlab, bitbucket) can be configured to use local installations.  The Bitbucket setting is:

https://github.com/Apicurio/apicurio-studio/blob/master/back-end/hub-core/src/main/java/io/apicurio/hub/core/config/HubConfiguration.java#L56-L57

You can control it either via a system property or an ENV variable.  

The steps to configuring a local Apicurio installation to use a local Bitbucket instance would be very similar to what is documented for GitLab.  For example, you'll need a local instance of Keycloak and you'll need to configure Keycloak and the local Bitbucket instance to work together to provide account linking.  Some documentation that can help can be found here:

https://apicurio-studio.readme.io/docs/setting-up-keycloak-for-use-with-apicurio#section-73-enable-bitbucket-account-linking

**However**, please note that the GitLab support for a local installation is the only one of the three that has been tested --- because it's the only one with an easily (and freely) installable test instance.  So I was able to test using GitLab by using their GitLab CE docker image.  The other systems (including Bitbucket) aren't so easily tested, and without ready access to local instances I have been unable to test them.

The good news is that I'd LOVE it if someone else had such a system and could test things out.  I'm happy to fix any bugs found, of course.  I'm also very happy to accept PRs fixing said bugs.

**Comment by jamesgallagher-ie** [comment]
Thanks so much Eric! I'll test as much as I can - this is a solo side-project so it may well be slow if I encounter issues with our Bitbucket setup as I'll have to raise tickets to make progress.

**Comment by EricWittmann** [comment]
No worries - good luck and let me know if I can help.
