### ISSUE TITLE
Apicurio Studio Beta 2.19 - Github linking authentication error

### ISSUE THREAD

**Issue by ablaas-ald** [Apicurio/apicurio-studio#564]
When linking Apicurio Studio 2.19 to Github (new account) I get the following error:

```
We're sorry...
Unexpected error when authenticating with identity provider
```

![image](https://user-images.githubusercontent.com/46496046/51071269-9683f000-164e-11e9-8ce2-147150db7684.png)

And the status is `Link initiated, awaiting completion...`
![image](https://user-images.githubusercontent.com/46496046/51071275-a56aa280-164e-11e9-8552-782570922643.png)

Thank you!

**Comment by EricWittmann** [comment]
Can you provide some information about your configuration?  Is this using the hosted **Try Live** version or did you install it locally?  I'm assuming it's the latter - and if so can you describe the configuration?

The account linking functionality is the hardest to configure because there are a bunch of different settings that need to be set up in various places (oauth config).

**Comment by ablaas-ald** [comment]
Thanks Eric for your prompt responses!

Actually, it's with the "Try Live" configuration. But I use email/pwd to login -didn't use Github or other account.

**Comment by EricWittmann** [comment]
That's ok - you should be able to register with email/pwd but still link a GitHub account.  Can you describe what happens when you try this?  Does it take you through the process of authentication/authorization on github.com or does it fail before that?

In other words, what exactly happens from the time you click "Link" on the settings page to the time you get the above error?

Also if you don't mind revealing it, what email address did you use to register?  If I know that I can check for issues on the server.

**Comment by ablaas-ald** [comment]
I worked correctly the first time I clicked "Link". 
I used the new account ablaas-ald, and then I started getting that error.

Now, if I unlink and try to link again, it throws the error.

I'm using ablaad (at) gmail.com  as user.

Thanks!

**Comment by EricWittmann** [comment]
OK I think you meant you're using ablaas (at) gmail - so I went ahead and reset the GitHub link for that account.  Can you try again and see if it works now?

**Comment by EricWittmann** [comment]
Sounds good, thanks!  And good luck.
