### ISSUE TITLE
Cannot add aws open api extension metadata

### ISSUE THREAD

**Issue by stephenwil** [Apicurio/apicurio-studio#669]
Hi,
  There's no way to add in cloud integration metadata such as the following, which form part of a method descriptor.

```
"x-amazon-apigateway-request-validator": "Validate query string parameters and headers",
        "x-amazon-apigateway-integration": {
          "credentials": "arn:aws:iam::123456789012:role/apigAwsProxyRole",
          "responses": {
            "default": {
              "statusCode": "200",
              "responseParameters": {
                "method.response.header.operator": "integration.response.body.op",
                "method.response.header.operand_2": "integration.response.body.b",
                "method.response.header.operand_1": "integration.response.body.a"
              },
              "responseTemplates": {
                "application/json": "#set($res = $input.path('$'))\n{\n    \"result\": \"$res.a, $res.b, $res.op => $res.c\",\n  \"a\" : \"$res.a\",\n  \"b\" : \"$res.b\",\n  \"op\" : \"$res.op\",\n  \"c\" : \"$res.c\"\n}"
              }
            }
          },
          "uri": "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:123456789012:function:Calc/invocations",
          "passthroughBehavior": "when_no_match",
          "httpMethod": "POST",
          "requestTemplates": {
            "application/json": "{\n    \"a\":  \"$input.params('operand1')\",\n    \"b\":  \"$input.params('operand2')\", \n    \"op\": \"$input.params('operator')\"   \n}"
          },
          "type": "aws"
        }
```

**Comment by EricWittmann** [comment]
Do you have some ideas about how Apicurio could support the entry of such information?  Specific integration with AWS perhaps?  What sort of user experience would you like to see?

**Comment by sandeepsuvit** [comment]
Hi Team,
Is there any way we can have this aws metadata definition added into the spec from the interface?
I assume we can add it via the `Source` tab, but any other option available via the interface itself?

**Comment by jsenko** [comment]
Hi,
Studio does not currently support adding extension properties using the visual interface, so you'll have to edit the source directly. If we wanted to add this feature, how would you like to see it work?

**Comment by jsenko** [comment]
@EricWittmann I think this could work if Studio supported JSON schemas, and you could separately define a JSON schema for extension properties. That way UI could generate forms based on the schema. WDYT?

**Comment by EricWittmann** [comment]
Overall I'm not in favor of generated forms in user interfaces.  Studio was specifically designed/created in a way that didn't utilize generated forms, because I don't think the resulting editing experience is good.

**However** - in the case of extension properties, I think it actually makes sense to allow registration of a JSON Schema for different extension properties (or groups of extension properties).  This would allow us to have some sort of visual editing experience beyond the Source tab.  So yes - I think this is a good idea.  I'm still not quite sure where we **display** the extension properties in the UI.  The OpenAPI spec supports extension properties in a wide array of locations (almost everywhere).  It's difficult to imagine how to visually incorporate support for extension properties in all of the locations possible to have them.

I'm extremely open to proposals of what the look and feel would be.  Not so much the look and feel of the editing of properties - that's probably just a modal dialog with the generated form suggested by @jsenko .  I'm more concerned about modifications to the existing editing experience that would visually indicate that extensions existed and how they could be selected/modified.  Also how to we visually indicate the places where extension properties have **not** yet been defined, but can be.

**Comment by dcu** [comment]
we're also needing this, couldn't apicurio at least respect the section and keep it as text? No need for a UI, at least for the first iteration

**Comment by EricWittmann** [comment]
Extension elements are now supported at various levels of the editor UI.
