### ISSUE TITLE
Create standalone docker distribution (based on docker compose)

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-studio#700]
We have the docker images to support a non-openshift based (docker compose) distribution.  Such a distro would be easier to both evaluate and deploy for users who do not have an OpenShift cluster available.

**Comment by EricWittmann** [comment]
My initial thought is to add a new folder in the `distro` section of the codebase:

https://github.com/Apicurio/apicurio-studio/tree/master/distro

It can contain the docker compose file, a Readme, and anything else needed to run that I'm not aware of. :)

**Comment by chriske** [comment]
Hey!

On the other issue (the WildFly), you asked me if I would like to contribute with the All-In-One compose bundle with Microcks. For some reason I didn't get the notification, but I'm here right now. When Nicnl contributes with the compose file, I can extend it to that All-in-one bundle with Microcks and KeyCloak.  Let me now if you want this :) And after it's done we can contribute that modification to Microcks too.

**Comment by Nicnl** [comment]
Hey  
Sorry for the delay, I don't have access to those compose files from home

I created a gist with two compose files:  
https://gist.github.com/Nicnl/652e70e7ba364cbb196fe4cdc5bd622d

- One for Keycloak and its database  
(Sorry Eric, I used the official `jboss/keycloak` container instead of your `apicurio-studio-auth`)
- One for Apicurio Studio

I stripped them as much as I could removing most of my environment-specific settings, hopefully keeping the absolute minimum  

However, there's a few points that are making me quite unconfortable:
- **The MySQL database**  
I used a MySQL database both for Keycloak and Apicurio  
But by doing so I encountered multiple issues, notably #683 and #688  
Could it be wiser to modify it and use a Postgres database instead?  
It's also possible to provide multiple _flavors_ of the compose files, giving the user the choice of picking his favorite database.  
I don't know.

- Even if I tried to strip those compose to their bare minimum, there's a few environment specific settings that I'm not able to remove:  
  - **The port mappings**  
    For now, I used the ports 8090 for Keycloak, 8091 for the API, 8092 for the websockets and 8093 for the UI  
    Those are hardcoded

  - **The environment variables of the UI container**  
    The UI container required the full endpoint URLs  
    My local server being `10.0.0.130`, I've configured this:  
      - `APICURIO_KC_AUTH_URL: 'http://10.0.0.130:8090/auth/'`
      - `APICURIO_UI_HUB_API_URL: 'http://10.0.0.130:8091'`
      - `APICURIO_UI_EDITING_URL: 'ws://10.0.0.130:8092'`
    
    I guess you're directly and transparently passing those variables to the UI.  
    That means that in the end, those variables must point to working endpoints wether the user opened the ports directly (like I did) or used a reverse proxy / ingress / whatever.
    
    I thought a bit about this, but I don't think there's any way to remove those.  

- **Ease of use**  
  I had great troubles figuring out what goes where and how everything goes together.  
  
  I'm thinking about GitLab as an example  
  The GitLab container fullfills an easy role: providing GitLab to the end user  
  The user starts the GitLab container, enter his configuration through either environment variables or config files, and it works
  
  So I'm wondering  
  Is there a need for the end user to know about the separate API, WS and UI parts of this project and setup them one by one manually?

**Comment by chriske** [comment]
Hi @Nicnl ,

thanks for the gist and for your thoughts!

I have some ideas:

- first of all, I think we should use some docker-compose environment files to be able to manage the credentials and URLs easilly
- we can create multiple combinations of compose files, like:
  **docker-compose -f apicurio-base.yml -f apicurio-mysql.yml up -d**
  In this scenario these config file will be merged, we just have to add combination specific environment files
- I can add an already configured nginx reverse proxy container, and we can "close" the currently opened ports into the host network. Only the nginx will be routed to the host and the browser will communicate with the other apps through that. (we can also add path prefixes and DNS support)
- if we want to achieve this, I think it is a good idea to create a bash and a batch script which can get the current ip of the host machine, write it to the specific files, and setup the infra
- of course it has the option to give the user SSL support, and I think we should do that too

What do you think @EricWittmann ?
Actually I'm starting to implement this based on the existing compose files. I'll let you know what I was able to achieve.

**Comment by pppttl** [comment]
Hi @chriske ,

Alternatively, you can use the $DOCKER_HOST_IP in docker-compose files. Similar to how [eventuate-tram does](http://eventuate.io/docs/usingdocker.html).

**Comment by Nicnl** [comment]
@pppttl

This is a very nice feature!  
I did not know that it's a thing  
Thank you!

**Comment by chriske** [comment]
Hi Guys!

I made the fiist version without the reverse proxy and SSL support, but "almost" everything is working.

https://github.com/chriske/apicurio-studio/tree/apicurio-studio-700/distro/docker-compose

Unfortunately the $DOCKER_HOST_IP is not working on every OS, so I didn't used it.

And there is an issue with Microcks, maybe the API changed on their side. The API definition, the example, and everything is OK, I can see them on the UI. But if I want to test it with the mock URL, it sends back nothing... No errors in the logs, just simply nothin. @EricWittmann do you have any ideas?

Besides that, I think the first iteration of this integrated environment is done.

**Comment by EricWittmann** [comment]
Hey everyone - I was out of the country last week for work and just back now, so am catching up on this thread.  Some really great stuff here!  I really appreciate the work done here, as I'm not really much of a docker expert. :)

I'll give this stuff a try as soon as I catch up with all the stuff I got behind on from last week!

I wonder if @lbroudoux has any thoughts about the microcks issue.  If not that's OK, I can dig into it later in the week hopefully.

**Comment by EricWittmann** [comment]
A contribution has been merged, the pull request is here:  https://github.com/Apicurio/apicurio-studio/pull/707

I encourage anyone interested to give it a try!
