### ISSUE TITLE
Specifiy 'Type Enum As ...' through UI

### ISSUE THREAD

**Issue by jjones09** [Apicurio/apicurio-studio#734]
It's currently possible to specify type as Enum through the UI, but this will then show up as an object in any example requests/responses though I'm actually returning a string.

Adding the type to the enum through the source view fixes this, and it allows the 'as' selector to be used in the UI - it would be nice if this was available through the UI initially without having to first manually place it in the source.

1. I add an Enum - no option to specify 'as'

![Screenshot 2019-04-15 at 09 35 08](https://user-images.githubusercontent.com/10963894/56118370-05305c80-5f62-11e9-9afa-59d03b7f7c7d.png)

2. Generated source - no 'type' property

![Screenshot 2019-04-15 at 09 35 15](https://user-images.githubusercontent.com/10963894/56118385-111c1e80-5f62-11e9-9f44-02574d3846b4.png)

3. Manually add 'type' property

![Screenshot 2019-04-15 at 09 36 27](https://user-images.githubusercontent.com/10963894/56118402-14170f00-5f62-11e9-8fb7-7f7404195bc6.png)

4. 'as' now available in UI

![Screenshot 2019-04-15 at 09 34 38](https://user-images.githubusercontent.com/10963894/56118487-1c6f4a00-5f62-11e9-8a18-bca61a46844b.png)

**Comment by EricWittmann** [comment]
Good point on this.  Thanks for the report.

**Comment by EricWittmann** [comment]
Additionally, setting a parameter to `enum` via the UI will result in a validation error of:

> Parameter `paramName` is missing a type.

So the user **should** definitely be able to set the enum type (and we should default to string initially).

**Comment by EricWittmann** [comment]
I have fixed this by having the UI default the `type` to `string`.  Currently the only way to change that is via the source tab, because I think that the vast majority of use-cases for `enum` will be as a `string`.  If anyone really needs the UI to support the ability to change the enum type to something else, please open another ticket.

Also note that I've improved the example generation to work better with enums (the generator will randomly pick one of the values).
