### ISSUE TITLE
Can't Reset Credentials / Forgot Password

### ISSUE THREAD

**Issue by csepulv** [Apicurio/apicurio-studio#746]
I was trying to use run locally, per instructions in [https://apicurio-studio.readme.io/docs/getting-started](https://apicurio-studio.readme.io/docs/getting-started.) It notes "The Apicurio Studio quickstart is configured to use an OpenShift Online instance of Keycloak for authentication"

This is fine, but there seems to be no way to delete my account nor even reset my password. When I try to go to [https://studio-auth.apicur.io/auth/realms/apicurio-local/protocol/openid-connect/forgot-credentials](https://studio-auth.apicur.io/auth/realms/apicurio-local/protocol/openid-connect/forgot-credentials), I can get error page back 

"We're sorry... Reset Credential not allowed"

How do I reset my credentials, change password, etc? (And how could I delete the account?)

**Comment by EricWittmann** [comment]
The quickstart is designed to be used for fast evaluation of Apicurio, which is why it uses the cloud version of Keycloak for authentication.  It does that so users don't have to install and configure Keycloak **and** Apicurio just to evaluate Apicurio.  As a result, the authentication server is configured very naively.

If you're looking to have Apicurio running with a more robust configuration, I would suggest installing your own authentication server (keycloak) and updating the Quickstart configuration to use that instead of the cloud instance.  There is documentation on how to achieve that here:

https://apicurio-studio.readme.io/docs/setting-up-keycloak-for-use-with-apicurio

Another option is to use Docker to run Apicurio rather than the quickstart.  Here is a nice docker compose feature that a community member contributed!

https://github.com/Apicurio/apicurio-studio/blob/master/distro/docker-compose/Readme.md

All of that being said - I can reset your account on the cloud auth server if you would like.  I would need your email address.

**Comment by csepulv** [comment]
Thanks. I will follow the instructions you sent.

For clearing the account, I will send you my email address. Closing this.
