### ISSUE TITLE
Apicurio will response a bit slowly when the open api file is large, such as 2M

### ISSUE THREAD

**Issue by yuanhuiliu** [Apicurio/apicurio-studio#791]
Apicurio will response a bit slowly when the open api file is large, such as 2M.

**Comment by EricWittmann** [comment]
Do you mean when editing?

Also if possible could you attach an example API design?

**Comment by yuanhuiliu** [comment]
Both editing and reading different operations are slowly. Please refer to the attached API design and rename it to xxxx.json first, thank you.
[mediacloud-wan.txt](https://github.com/Apicurio/apicurio-studio/files/3232319/mediacloud-wan.txt)

**Comment by EricWittmann** [comment]
Thanks for the sample document - I just loaded it and the performance really is terrible.  The main problem seems to be the list of **paths** and **data type** on the left - there are just so many of them, and clearly we're asking angular to do too much work to display them.  I'll start to look for ways to streamline that.  

For reference, there are 255 paths defined in this API, and 4 types.

One thing to note - if you use the "Search Everything" box to reduce the number of items being displayed, then performance becomes acceptable.  So that's good news and something I can hopefully address.  I'm guessing the primary issue is the aggregate validation error icon that may appear next to any of the paths in the left-hand master view.  That icon needs to appear or disappear depending on whether there are any validation problems anywhere in that path (which requires a search of the data model tree from that point down).  So it has to do that search for each item in the list.

I thought we were already caching the results in those icons - but perhaps that's not working.  It's something to explore, anyway.  I may skip this for now and see if there are some other easier to fix problems I can knock out before coming back to this later in the week. :)

**Comment by EricWittmann** [comment]
OK so the problem was, in fact, the validation problem aggregate control.  It's simply too slow to show the problem icon next to the master view items when there are too many items.  So as a temporary workaround for this (in order to make the editor more usable for large definitions), I have removed the validation problem aggregate icon when there are > 50 items in the master view.  In the future I'll need to look more carefully at the performance characteristics of the control itself.
