### ISSUE TITLE
An api project cannot be copied while Chinese character exists in the api document

### ISSUE THREAD

**Issue by yuanhuiliu** [Apicurio/apicurio-studio#794]
An api project cannot be copied while Chinese character exists in the api document, such as importing from the attached one (pls change the extension name to yaml first):
[WithChineseCharacter.txt](https://github.com/Apicurio/apicurio-studio/files/3232033/WithChineseCharacter.txt)

**Comment by EricWittmann** [comment]
The problem here was that the copy/import API functionality sends a base64 encoded string to the server.  Sadly the browser's built-in base64 encoding suffers from a unicode problem documented here:

https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#The_Unicode_Problem

The solution is to use a 3rd party library base64 library.  I have chosen https://www.npmjs.com/package/js-base64 mostly because it also had typescript definitions.
