### ISSUE TITLE
ApiCurio is not loading user activity, Recent APIs, Linked Accounts etc

### ISSUE THREAD

**Issue by 0x218** [Apicurio/apicurio-studio#810]
In association with previous discussion (https://github.com/Apicurio/apicurio-studio/issues/797), we created an F5 vip name (ssl enabled).  Objective is to have a SSL enabled ApiCurio either through F5 or Nginx so the GitHub linking works.
Now our setup is https://the-F5-vip-name/ -> http://nginx:80/ -> http://apicurio/ -> https://keycloak/.  Nginx and ApiCurio is hosted in same server.

ApiCurio is connecting to corporate KeyCloak for authentication and that part work flawlessly.  Problem comes after that  - 

May be some thing wrong in my setup, but : -
a.    **_Loading User activity_** and **_Loading Recent APIs_** widget just keeps spinning.
b.    APIs -> **_View All APIs_** returns **Connection Error(Could Not Reach Server)**
c.    Settings -> **_Validation_** and **_Linked Accounts_** are returning **Connection Error(Could Not Reach Server)**

![image](https://user-images.githubusercontent.com/38358669/59728278-06e6fc80-91ff-11e9-91f3-d916fed0b12a.png)

During this event my logs are limited to just these four lines: -  
[io.apicurio.studio.shared.config.Configuration] (default task-2) Config Property: APICURIO_UI_HUB_API_URL/apicurio-ui.hub-api.url = null
[io.apicurio.studio.shared.config.Configuration] (default task-2) Config Property: APICURIO_UI_EDITING_URL/apicurio-ui.editing.url = null
[io.apicurio.studio.shared.config.Configuration] (default task-2) Config Property: APICURIO_UI_HUB_UI_URL/apicurio-ui.url = null
[io.apicurio.studio.shared.config.Configuration] (default task-2) Config Property: APICURIO_UI_FEATURE_MICROCKS/apicurio-ui.feature.microcks = false

If I remove F5 vip name from the picture and access APICurio via Nginx (http), everything loads successfully (and ends up in "Unexpected error when authenticating with identity provider" as documented in https://github.com/Apicurio/apicurio-studio/issues/797).

Please advise.

**Comment by EricWittmann** [comment]
My best guess is that what you want to do in this situation is make sure that the Apicurio UI accesses the back-end through the F5 using **https**.  You've blocked out the domain names from all the URLs in the screen shot (which is appropriate obviously) so this is just guessing.  However, since all those URLs are **http** rather than **https** I'm going to assume they are wrong (i.e. pointing to the wrong place).

Here is how you can configure Apicurio's UI to access the correct back-end services.  You can set the following system properties wherever you are running the UI (this depends on whether you're running Apicurio all-in-one or split across multiple docker images):

* `apicurio-ui.hub-api.url` : set this to the URL of the back-end REST API
* `apicurio-ui.editing.url` : set this to the URL of the back-end websocket API

Based on the information in the screenshot you included, it appears you are running the Apicurio quickstart in Wildfly (the URLs are different depending on how you're running things). So my best guess on what you should set these things to is:

```
apicurio-ui.hub-api.url=https://the-f5-vip-name/api-hub/
apicurio-ui.editing.url=wss://the-f5-vip-name/api-editing/
```

The only other option I can think of is that your F5 is not configured to properly route traffic to `/api-hub` and `/api-editing`.

Now here are some things you can do to make sure stuff is configured:

* Check the UI's `config.js` file to verify the URLs it needs are correct.  Do this by accessing this URL:  https://the-f5-vip-name/studio/config.js
* Check that the REST API is available by accessing this URL:  https://the-f5-vip-name/api-hub/system/status

**Comment by 0x218** [comment]
@EricWittmann that helped.  Thank you very much.

Below are the steps we did to resolve the issue - 
a.    Added below stanza under _system-properties_
_property_ name="apicurio-ui.hub-api.url" value="https://the-f5-vip-name/api-hub/"_
_property name="apicurio-ui.editing.url" value="wss://the-f5-vip-name/api-editing/"_
b.    Add certificates of _https://github.com_ and _https://api.github.com_ to the Keycloak Java truststore.
c.  The _Web Origins_ field of KeyCloak client must be set to *****

With this I can -> F5 Vip -> Nginx -> KeyCloak -> ApiCurio <-> GitHub.  
Thank you for developing ApiCurio.

**Comment by 0x218** [comment]
@EricWittmann that helped.  Thank you very much.

Below are the steps we did to resolve the issue - 
a.    Added below stanza under _system-properties_
_property_ name="apicurio-ui.hub-api.url" value="https://the-f5-vip-name/api-hub/"_
_property name="apicurio-ui.editing.url" value="wss://the-f5-vip-name/api-editing/"_
b.    Add certificates of _https://github.com_ and _https://api.github.com_ to the Keycloak Java truststore.
c.  The _Web Origins_ field of KeyCloak client must be set to *****

With this I can -> F5 Vip -> Nginx -> KeyCloak -> ApiCurio <-> GitHub.  
Thank you for developing ApiCurio.

**Comment by EricWittmann** [comment]
Glad you got it working!
