### ISSUE TITLE
How to change email?

### ISSUE THREAD

**Issue by andrewhoodec** [Apicurio/apicurio-studio#871]
I created an apicurio account with github. I changed the email associated with my github account.

How can I update the email in my apicurio profile? Or maybe a way to delete & recreate the account?

I tried unlinking and re-linking my github account, but it looks like email is stored permanently to apicurio account.

**Comment by EricWittmann** [comment]
You can try changing your email address in Apicurio here:

https://studio-auth.apicur.io/auth/realms/apicurio/account/

I'm not sure if that will do what you want, however, because we're using email address as the unique userId, and I don't think changing that setting will also change the userId.

If that doesn't do what you want, then I can delete your user account (just PM me your email address for confirmation).

Please note that if we do successfully change your userId (either by changing it or deleting your user account), then any APIs you had access to will no longer be yours (each API has an **owner** that is the userId of the creator).  So I would recommend that if you have any APIs you don't want to lose, you do one of two things first:

1. Download the API content so you can re-upload it after
** OR **
2. Create an collaborator invitation link for yourself for each API - save those URLs and then use them once you have a new/changed user account

**Comment by andrewhoodec** [comment]
Thanks that worked, and yes I lost access to the APIs, but I'm not the owner so should be ok :)
