### ISSUE TITLE
"You have unsaved changes"

### ISSUE THREAD

**Issue by timchase01** [Apicurio/apicurio-studio#879]
Throughout today I have been making changes in Apicurio Studio and it is giving the following message when I try to navigate away.

"You have 189 unsaved changes.  Are you sure to close the page?"

I would really hate to lose all of these changes.  Is there a way to force it to post those changes?

The disconnected work offline button is not there.  So it is acting as if I am working online, it just doesn't want to commit my changes up to the server for some reason?

How do I proceed?

**Comment by EricWittmann** [comment]
The bug has been fixed.  however unfortunately for you the only recourse is
to switch to the source tab and copy the content from there so you don't
lose your changes.  you could try disabling your ethernet on your computer
and then reconnecting.  That could trigger a disconnect from the server
requiring the browser reconnect.

**Comment by timchase01** [comment]
Thanks Eric.  Appreciate the help.

**Comment by EricWittmann** [comment]
What did you end up doing?  I'm curious if unplugging your ethernet (to force "offline" mode) and then plugging it back in worked. :)

**Comment by EricWittmann** [comment]
You would probably also have needed to re-authenticate in another tab... :(

I think I still have some additional improvements to make in resiliency.

**Comment by timchase01** [comment]
I unfortunately lost it all.  I came in this morning and my PC decided it needed to install updates overnight, so it closed the browser.  :(     Working great so far today though.

**Comment by EricWittmann** [comment]
Ugh!  Sorry to hear that.  One major improvement I would like to make in the future is to store "pending" changes to browser local storage and then remove them once the server confirms they have been applied.  That would at least ensure that changes are not lost.

Also, for anyone encountering this issue in the future, the bug that causes this problem is documented in https://github.com/Apicurio/apicurio-studio/issues/878.
