### ISSUE TITLE
[Question] Using another SSO than Keycloak for authentication

### ISSUE THREAD

**Issue by HugoSentelien** [Apicurio/apicurio-studio#964]
Hello,

First of all, thank you Red Hat, @EricWittmann and all members of his team for this great product!

I was just asking myself if it could be possible to use another pre existing SSO server for Apicurio?

I know they are both Redhat's software, but, most of the company which need an OpenAPI editor already have another SSO server. So, I would like to know what do you think would be the best solution in this case? Is it planned in your Roadmap?

Would you recommend me to create a Keycloak server linked to the already existing SSO server? (as writen on https://www.keycloak.org/docs/7.0/server_admin/ : "You can also hook Keycloak to delegate authentication to any other OpenID Connect or SAML 2.0 IDP.").

Honestly, I am even thinking of using this project: https://github.com/EricWittmann/apicurito-prod , to lose all the connexion with Git servor, to lose all the features developped during the year (the interface has really been improved) and to lose all the online things just to be able to use it without Keycloak as the SSO server 😦

Thank you for your time and your understanding, I am doing this as a public issue because I saw nothing about this subject.

**Comment by EricWittmann** [comment]
Thanks for the question, Hugo.  Currently Apicurio Studio does not support any other SSO servers.  Right now we use Keycloak for two things:

1) SSO/authentication into the UI and API layers
2) Managing "account linking" between the KC/Apicurio user and their GH/GL/Bitbucket account

It would NOT be difficult to support (1) for an SSO other than Keycloak.  If you wanted to explore contributing support for some alternative SSO solution I would be happy to guide you.  If we did this, we could also introduce some global config options to disable Account Linking support.  We would do this because the support for (2) is more difficult to replace.  Keycloak provides all of the auth integration needed to allow Apicurio to link the user's account to their e.g. GitHub account.  This allows Apicurio to make authenticated calls to the GitHub API on behalf of the Apicurio user.

Certainly you can use Keycloak as a proxy to another SSO (as you linked above) so that no functionality is lost.  But of course you are then running yet another server. 

Apicurito is another option as well, but you lose quite a lot of functionality by using that.  Apicurito is a very simple application with ZERO back-end at all.  It's just the API Designer in a client-only web application.  It has no persistence, no git integration, no collaboration, no auditing, etc etc.  If you do go that route, I recommend this version:

https://github.com/apicurio/apicurito

**Comment by HugoSentelien** [comment]
Hello,

Thank you for the fast and complete answer. Honestly, I still think apicurio is the best for a beginner because of everything being in UI. But the lack of features in text made it hard to have experienced developers to use it, and they are also those who will be supposed to help the beginner.

So, they have chosen another solution in my use case, and so, I will not be able to get any time to develop for alternative solution.

But, thank you again for your answer, and I hope it will help other people who will have the opportunity to do it.

Wish you all the best!

**Comment by EricWittmann** [comment]
OK no problem, Hugo.  If you had some time to enumerate exactly what your experienced developers wanted, that would be super helpful.  It sounds like maybe they just wanted a better "source code" editing experience (similar to what you get from e.g. Swagger Editor).  But if there is anything more specific than that I'd love to hear it.

If you don't have bandwidth to provide detailed feedback that's totally fine too. :)  It's just always helpful to get feedback from folks who have tried the software.

**Comment by HugoSentelien** [comment]
Yes Eric, exactly, the limitations of messages about source code editing made a big difference like:
You can't save a file when you make an error in source code editing, but you don't really know where you need to change your source code specification
The instant feed back of the "source code" editing, being able to see really fast without having to do anymore action how the source code editing change the developer's specifications.

It was the main difference for experienced developers, they were also big fans of the "try it out" with the "authorization" ability in the same interface.

Well, Apicurio is great, the UI is really intuitive and better in each version.
There is the "repository" to share easily the API specification, and you can easily work from a git project, which is a perk I didn't see on the others ones.
So, from my point of view, only the "source code" editing is behind some solutions, and I wish you all the best to be able to make it great too ;)

**Comment by EricWittmann** [comment]
Thanks for the feedback @HugoSentelien  - it's appreciated! :)
